### ISSUE TITLE
Error on `next dev`

### ISSUE THREAD

**Issue by zackhitch** [wutali/nextjs-netlify-blog#36]
After I've run `yarn install`, and then run `yarn run dev` I get this error: `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in ...` and the app will not run.

**Comment by facinick** [comment]
Getting this error:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/facinick/Workspace/drakapoor/node_modules/next/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:400:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at mod._resolveFilename (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 552 (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __nccwpck_require__ (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 270 (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __nccwpck_require__ (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 327 (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/Users/facinick/Workspace/drakapoor/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
```

Steps to reproduce:

```
yarn install
yarn dev
```

Node JS Version: `v18.13.0`
NPM Version: `8.19.3`
Yarn Version: `1.22.19`

**Comment by facinick** [comment]
Update:

Started running successfully once I switched to Node version `12.13.0`

**Comment by sergey-safarov** [comment]
I have successfully installed the template with PR https://github.com/wutali/nextjs-netlify-blog-template/pull/50
And using NodeJS 16 on `Netlify`
